version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  elasticsearch:
    image: 'elasticsearch:7.9.2'
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'

  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "task_manager.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - rabbitmq
      - elasticsearch

  celery:
    build: .
    command: celery -A test_work worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
      - elasticsearch

  flower:
    build: .
    command: celery -A test_work flower --port=5555
    ports:
      - '5555:5555'
    depends_on:
      - db
      - rabbitmq
      - elasticsearch
